add support for redis v4
animir/node-rate-limiter-flexible pull request #176
Opened 2022-08-24 04:02 UTC by rahil-p

Related: #141, #167

This pull request implements `RateLimiterRedisNext`, which is intended to be exclusively compatible with [node-redis](https://github.com/redis/node-redis) v4.x.

2022-08-24 04:18 UTC, rahil-p commented
I haven't written tests for these changes, and I'm not sure I'll be available to.

For anyone who may be interested in writing tests:
It will probably require something other than mock-redis (which isn't compatible with the new node-redis clients).  I've used [testcontainers](https://www.npmjs.com/package/testcontainers) in the past for testing integrations with node-redis 4 ([connect-redis-session](https://github.com/rahil-p/connect-redis-session)), but it may be overkill.

2022-08-24 12:44 UTC, animir commented
@rahil-p Hey, this is great!

However, we can't create other class for this case. This will be confusing for everyone except you and me.

2022-08-24 12:55 UTC, animir commented
@rahil-p I believe, RateLimiterRedis can be improved for `redis` v4+ with additional 5-6 if/else conditions. Is it possible to check if it is `redis` package and version is 4+ ? If yes, it would be good.

Yes, it would be not the best code structure and agains some best practice, but `rate-limiter-flexible` users would be glad for the result not code :)

2022-08-24 20:00 UTC, rahil-p commented
@animir Thanks for the feedback.  I agree that that's the better solution for users of the package.

I'm not sure what the best way to approach checking if the provided client is from `redis` v4.  I can dig in and follow up - suggestions are welcome.

2022-08-24 20:07 UTC, rahil-p commented on lib/RateLimiterRedisNext.js
> +        arguments: [String(points), String(msDuration)],
This needs to be fixed.  The Lua script expects the expire time in seconds, but milliseconds are provided.

2022-08-25 11:19 UTC, animir commented
@rahil-p If there is no way to get `node-redis` client version, [storeType](https://github.com/animir/node-rate-limiter-flexible/wiki/Options#storetype) limiter option can be used to set it. It could be set to `redis4+` and then checked in `_upsert` and other functions, where redis client used.

2022-09-04 19:01 UTC, animir requested changes

2022-09-04 19:01 UTC, animir commented on lib/RateLimiterRedis.js
> +      } else if (secDuration > 0) {
@rahil-p Could you explain, why do you edit this block?

2022-09-04 19:01 UTC, animir commented on lib/RateLimiterRedis.js
> +          return multi.pTTL(rlKey).exec(true);
@rahil-p Have you tested this code? It looks like Promise returned from `_upsert` is never rejected or resolved. The same is for other two `return` lines below.

2022-09-04 19:01 UTC, animir commented on lib/RateLimiterRedis.js
> +          return result;
@rahil-p It is also not resolved or rejected. And the line above.

2022-09-05 00:59 UTC, rahil-p commented on lib/RateLimiterRedis.js
> +          return multi.pTTL(rlKey).exec(true);
I haven't tested/reviewed any of changes from the most recent commit yet (made a quick push while traveling).


You're right, this Promise does not resolve - the if block I added isn't in the correct scope.  I'll take some time to review this PR's changes tonight and fix any issues.

2022-09-05 01:43 UTC, rahil-p commented on lib/RateLimiterRedis.js
> +      } else if (secDuration > 0) {
I didn't change this directly (was an autofix), but it doesn't comply with the project's ESLint config.  The specific rule is [`no-lonely-if`](https://eslint.org/docs/latest/rules/no-lonely-if), which this project inherits from the Airbnb config ([source](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L285)).  

I'll revert the change - let me know if you'd like me to take another course of action (like using disable comments or modifying the ESLint rules).

2022-09-05 02:34 UTC, rahil-p commented on lib/RateLimiterRedis.js
> +          return this.client.eval(this._scripts.increment, {
This eval won't work, since `this._scripts.increment` does not point to anything (should use `incrTtlLuaScript`).

2022-09-05 02:52 UTC, rahil-p commented on lib/RateLimiterRedis.js
> +          const incrCallback = (err, result) => {
Here's another change that was made by an ESLint autofix.  Please let me know if you'd like me to revert it.

Comparing to base:
```diff
- const incrCallback = function(err, result) {
+ const incrCallback = (err, result) => {
```

2022-09-27 14:12 UTC, marlonelima commented
Something new?

2022-09-28 18:49 UTC, animir commented
@marlonelima Nothing the for the last month. If you wish to help, you can look at these changes and implement redis package v4+ support. Let us know.

2022-10-06 19:19 UTC, rahil-p commented
I pushed changes in d110583 that need review. My availability has been limited, so I haven't been able to manually test out these changes. I'd appreciate if someone could give that a go.

2022-11-18 02:10 UTC, a-r-d commented
@rahil-p I was just trying to test your changes and I got this error
```
    ERR Error running script (call to f_a1de965f42e177aa339706bd580f049065eca79a): @user_script:1: @user_script: 1: Lua redis() command arguments must be strings or integers

```

I did set the client store version to 4:
![Screenshot from 2022-11-17 21-08-49](https://user-images.githubusercontent.com/1312019/202600441-b34bdbb6-6312-4848-9997-37c964a0b3c3.png)

I really do want to use change though, I think it would be really nice since the 3.x version of redis module is very out of date and doesnt even have proper typescript types.

2023-03-10 12:43 UTC, manzan46 commented
👋 For what it's worth I just test this PR and it's working with a basic rate limiting setup, so I don't think it's far and would be really useful to have it merged :)  

```
    blockDuration: 30,
    duration: 10,
    points: 20,
    keyPrefix: 'rate-limite-key',
     keyFn: req => req.userId,
```
 
 might be worth also adding a section to the Redis wiki to add `clientStoreVersion` as options when creating the Rate limiter: 
 
 ```
     const rateLimiterRedis = new RateLimiterRedis({
      storeClient: redisClient, // same as now
      ... // all the classic options
      clientStoreVersion: 4,
    });
    ```

2023-03-10 12:55 UTC, animir commented
@manzan46 Hi, a-r-d tested it and found an error a couple of months ago. There were no changes since then. Also, new code requires new tests to be written. Unfortunately, It can't be merged without tests. While this PR looks promising, it can't be merged like this.

2023-03-10 12:59 UTC, manzan46 commented
> @manzan46 Hi, a-r-d tested it and found an error a couple of months ago. There were no changes since then. Also, new code requires new tests to be written. Unfortunately, It can't be merged without tests. While this PR looks promising, it can't be merged like this.

No problems at all, it was mainly to mention on basic usecase I didn't have any issue on my side, and try to get the ball rolling 😅  (definitely better to merge this with test 👌🏻 )

2023-08-27 15:28 UTC, closed without merging

2023-08-27 15:28 UTC, animir commented
Closing this PR. Changes arrived in the scope of other PR https://github.com/animir/node-rate-limiter-flexible/pull/218. Thank you.

2023-08-29 10:55 UTC, animir commented
Support of `ioredis` v4+ added in [3.0.0](https://github.com/animir/node-rate-limiter-flexible/releases/tag/v3.0.0).